/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ArkQrcode {
    'address': string;
    'amount': number;
    'deserializeURI': (uri: string) => Promise<{ address: any; amount: any; label: any; vendorField: any; }>;
    'fromObject': (data: any) => Promise<HTMLElement>;
    'getDataURL': (mime?: string) => Promise<string>;
    'getURI': () => Promise<string>;
    'label': string;
    'showLogo': boolean;
    'size': number;
    'validateURI': (uri: string) => Promise<RegExpExecArray>;
    'vendorField': string;
  }
}

declare global {


  interface HTMLArkQrcodeElement extends Components.ArkQrcode, HTMLStencilElement {}
  var HTMLArkQrcodeElement: {
    prototype: HTMLArkQrcodeElement;
    new (): HTMLArkQrcodeElement;
  };
  interface HTMLElementTagNameMap {
    'ark-qrcode': HTMLArkQrcodeElement;
  }
}

declare namespace LocalJSX {
  interface ArkQrcode extends JSXBase.HTMLAttributes<HTMLArkQrcodeElement> {
    'address'?: string;
    'amount'?: number;
    'label'?: string;
    'showLogo'?: boolean;
    'size'?: number;
    'vendorField'?: string;
  }

  interface IntrinsicElements {
    'ark-qrcode': ArkQrcode;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


