/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ArkQRCode as ArkQrcode
} from './components/ark-qrcode/ark-qrcode';

declare global {
  interface HTMLArkQrcodeElement extends ArkQrcode, HTMLElement {
  }
  var HTMLArkQrcodeElement: {
    prototype: HTMLArkQrcodeElement;
    new (): HTMLArkQrcodeElement;
  };
  interface HTMLElementTagNameMap {
    "ark-qrcode": HTMLArkQrcodeElement;
  }
  interface ElementTagNameMap {
    "ark-qrcode": HTMLArkQrcodeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ark-qrcode": JSXElements.ArkQrcodeAttributes;
    }
  }
  namespace JSXElements {
    export interface ArkQrcodeAttributes extends HTMLAttributes {
      address?: string;
      amount?: number;
      label?: string;
      showLogo?: boolean;
      size?: number;
      vendorField?: string;
    }
  }
}

